
#line 2 "lex.parser_.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer parser__create_buffer
#define yy_delete_buffer parser__delete_buffer
#define yy_flex_debug parser__flex_debug
#define yy_init_buffer parser__init_buffer
#define yy_flush_buffer parser__flush_buffer
#define yy_load_buffer_state parser__load_buffer_state
#define yy_switch_to_buffer parser__switch_to_buffer
#define yyin parser_in
#define yyleng parser_leng
#define yylex parser_lex
#define yylineno parser_lineno
#define yyout parser_out
#define yyrestart parser_restart
#define yytext parser_text
#define yywrap parser_wrap
#define yyalloc parser_alloc
#define yyrealloc parser_realloc
#define yyfree parser_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 3
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    #define yy_create_buffer parser__create_buffer

    #define yy_delete_buffer parser__delete_buffer

    #define yy_scan_buffer parser__scan_buffer

    #define yy_scan_string parser__scan_string

    #define yy_scan_bytes parser__scan_bytes

    #define yy_init_buffer parser__init_buffer

    #define yy_flush_buffer parser__flush_buffer

    #define yy_load_buffer_state parser__load_buffer_state

    #define yy_switch_to_buffer parser__switch_to_buffer

    #define yypush_buffer_state parser_push_buffer_state

    #define yypop_buffer_state parser_pop_buffer_state

    #define yyensure_buffer_stack parser_ensure_buffer_stack

    #define yylex parser_lex

    #define yyrestart parser_restart

    #define yylex_init parser_lex_init

    #define yylex_init_extra parser_lex_init_extra

    #define yylex_destroy parser_lex_destroy

    #define yyget_debug parser_get_debug

    #define yyset_debug parser_set_debug

    #define yyget_extra parser_get_extra

    #define yyset_extra parser_set_extra

    #define yyget_in parser_get_in

    #define yyset_in parser_set_in

    #define yyget_out parser_get_out

    #define yyset_out parser_set_out

    #define yyget_leng parser_get_leng

    #define yyget_text parser_get_text

    #define yyget_lineno parser_get_lineno

    #define yyset_lineno parser_set_lineno

    #define yywrap parser_wrap

    #define yyalloc parser_alloc

    #define yyrealloc parser_realloc

    #define yyfree parser_free

    #define yytext parser_text

    #define yyleng parser_leng

    #define yyin parser_in

    #define yyout parser_out

    #define yy_flex_debug parser__flex_debug

    #define yylineno parser_lineno

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE parser_restart(parser_in  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int parser_leng;

extern FILE *parser_in, *parser_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up parser_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up parser_text again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via parser_restart()), so that the user can continue scanning by
	 * just pointing parser_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when parser_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int parser_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow parser_wrap()'s to do buffer switches
 * instead of setting up a fresh parser_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void parser_restart ( FILE *input_file  );
void parser__switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE parser__create_buffer ( FILE *file, int size  );
void parser__delete_buffer ( YY_BUFFER_STATE b  );
void parser__flush_buffer ( YY_BUFFER_STATE b  );
void parser_push_buffer_state ( YY_BUFFER_STATE new_buffer  );
void parser_pop_buffer_state ( void );

static void parser_ensure_buffer_stack ( void );
static void parser__load_buffer_state ( void );
static void parser__init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER parser__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE parser__scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE parser__scan_string ( const char *yy_str  );
YY_BUFFER_STATE parser__scan_bytes ( const char *bytes, int len  );

void *parser_alloc ( yy_size_t  );
void *parser_realloc ( void *, yy_size_t  );
void parser_free ( void *  );

#define yy_new_buffer parser__create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        parser_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            parser__create_buffer(parser_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        parser_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            parser__create_buffer(parser_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *parser_in = NULL, *parser_out = NULL;

typedef int yy_state_type;

extern int parser_lineno;
int parser_lineno = 1;

extern char *parser_text;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr parser_text

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up parser_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	parser_leng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[251] =
    {   0,
        0,    0,    6,    6,   12,   12,   19,   19,    3,    3,
       93,   91,   88,   89,   90,   91,   80,   91,   72,   64,
       65,   83,   81,   82,   77,   84,   55,   59,   70,   69,
       78,   74,   79,   43,   60,   60,   60,   55,   55,   62,
       63,   86,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   66,   71,   67,    6,    8,
        7,   16,   12,   92,   16,   16,   19,   20,   19,    3,
        4,   92,    1,   88,   75,   68,    0,    0,    0,    0,
        0,   17,   73,   76,    5,   87,   55,   59,   60,   55,
       61,   85,   60,   61,    0,   60,   61,    0,    0,   61,

       61,   61,   61,   61,   61,   61,   61,   28,   52,   61,
       61,   61,   61,   61,   61,   61,   29,   61,   39,    6,
        7,    7,    9,   12,    0,   15,   14,   19,   18,    3,
        0,    0,    0,    0,    0,    0,   87,   37,   61,   57,
       36,   61,   56,    0,   61,   44,   61,   61,   61,   61,
       61,   61,   61,   35,   61,   61,   61,   61,   61,   61,
       61,   13,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   34,   33,    0,   61,   61,   61,   51,   53,   61,
       61,   61,   32,   61,   61,   61,   31,   61,   50,    0,
        0,    0,    0,    0,    0,   25,    0,    0,   58,   61,

       47,   40,   54,   46,   61,   61,   61,   38,   49,   61,
        2,    0,   22,   21,    0,    0,    0,   27,   61,   61,
       30,   45,   61,    0,    0,   26,   24,   61,   61,   61,
       10,    0,   61,   61,   61,    0,   23,   61,   48,   61,
        0,   61,   61,    0,   61,   42,    0,   41,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    2,    1,    7,    8,    9,   10,   11,
       12,   13,   14,    1,   15,   16,   17,   18,   18,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,    1,   25,   26,   26,   26,   26,   26,   26,
       27,   28,   29,   29,   29,   29,   30,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   31,
       32,    1,   33,   34,   35,    1,   36,   37,   38,   39,

       40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   45,   52,   53,   54,   55,   45,   56,   57,
       58,   59,   60,   61,   62,   63,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    4,    1,    5,    5,    5,    6,    6,    1,
        1,    1,    1,    7,    1,    6,    6,    6,    6,    6,
        6,    1,    1,    1,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    1,
        1,    3,    5
    } ;

static const flex_int16_t yy_base[263] =
    {   0,
        0,    0,   61,   62,   75,    0,   63,   64,  136,  137,
      435,  436,   68,  436,  436,  411,  436,  133,  424,  436,
      436,  436,  436,  436,  416,  129,  129,  143,  436,  436,
      436,  436,  407,  436,   50,  147,  135,  172,  149,  183,
      436,  436,  377,  143,  102,    0,  145,  373,  155,  148,
      388,  373,  170,  149,  376,  436,  436,  436,    0,  436,
      195,  436,  211,  436,  401,    0,    0,  436,  362,    0,
      436,  401,  436,  212,  436,  436,  373,  381,  384,  364,
      364,  436,  436,  436,  436,    0,  197,    0,  132,  200,
        0,  436,  202,  366,  217,  205,  365,  220,  405,  356,

      359,  372,  361,  361,  356,  369,  355,    0,    0,  352,
      346,  353,  355,  359,  180,  348,    0,  351,    0,    0,
      382,  220,  436,  237,  374,  436,  373,    0,    0,    0,
        0,  194,  348,  347,  340,  357,    0,    0,  339,  236,
        0,  338,  436,  241,  341,    0,  353,  350,  348,  346,
      341,  334,  343,    0,  329,  331,  340,  337,  338,  337,
      338,  436,  351,  327,  318,  317,  331,  320,  329,  317,
      315,    0,    0,  247,  328,  319,  318,    0,    0,  322,
      310,  309,    0,  308,  307,  318,    0,  303,  313,  231,
      300,  300,  299,  300,  299,  436,  295,  295,  436,  305,

        0,    0,    0,    0,  295,  288,  292,    0,    0,  309,
      238,  304,  436,  436,  293,  278,  276,  436,  294,  267,
        0,    0,  258,  265,  267,  436,  436,  227,  227,  237,
      261,  228,  234,  218,  218,  216,  436,  216,    0,  228,
      223,  218,  197,  190,  186,    0,  172,    0,  436,  436,
      280,  287,  294,  183,  301,  308,  311,  314,  320,  327,
      334,  157
    } ;

static const flex_int16_t yy_def[263] =
    {   0,
      250,    1,  251,  251,  250,    5,  252,  252,  253,  253,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  254,  254,  250,  250,
      250,  250,  250,  250,   28,   28,   28,   28,   28,  250,
      250,  250,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  250,  250,  250,  255,  250,
      256,  250,  250,  250,  257,  258,  259,  250,  259,  260,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  261,   28,   28,   28,   28,
      254,  250,   28,  254,  250,   28,  254,  250,  250,  254,

      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  255,
      256,  256,  250,  250,  257,  250,  258,  259,  259,  260,
      262,  250,  250,  250,  250,  250,  261,  254,  254,  250,
      254,  254,  250,  250,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      254,  250,  262,  250,  250,  250,  250,  250,  250,  250,
      250,  254,  254,  250,  254,  254,  254,  254,  254,  254,
      254,  254,  254,  254,  254,  254,  254,  254,  254,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  254,

      254,  254,  254,  254,  254,  254,  254,  254,  254,  254,
      250,  250,  250,  250,  250,  250,  250,  250,  254,  254,
      254,  254,  254,  250,  250,  250,  250,  254,  254,  254,
      250,  250,  254,  254,  254,  250,  250,  254,  254,  254,
      250,  254,  254,  250,  254,  254,  250,  254,  250,    0,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250
    } ;

static const flex_int16_t yy_nxt[500] =
    {   0,
       12,   13,   14,   15,   13,   16,   17,   18,   19,   12,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   34,   35,   36,   37,   35,   38,
       39,   40,   41,   42,   35,   43,   44,   45,   46,   47,
       46,   46,   48,   49,   46,   50,   46,   51,   46,   52,
       46,   53,   54,   55,   46,   46,   46,   46,   46,   56,
       57,   58,   12,   60,   60,   68,   68,   89,   89,   74,
       69,   69,   74,   61,   61,   62,   63,   64,   62,   63,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   65,
       65,   65,   65,   65,   62,   62,   66,   62,   62,   62,

       65,   65,   65,   65,   65,   65,   62,   62,   62,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   62,   62,   62,   65,   71,   71,
       76,   85,   72,   72,   95,   86,   87,   88,  103,   89,
       89,  104,   89,   89,   89,   89,   89,   89,   90,   90,
       88,   88,  163,   89,   89,   89,   90,   89,   89,   89,
       89,   89,   89,   89,   93,  111,   77,   89,   90,   90,
       78,   79,   80,   94,  112,   81,  101,   98,   91,   90,
       89,  105,   82,  106,  102,  109,  107,   73,   73,   96,

       98,   90,   90,  110,  117,  115,  118,  122,   97,  116,
       99,  123,  124,   74,   87,  124,   74,   90,   89,   89,
       89,  140,   89,   89,   98,  249,   90,   90,  158,   90,
       90,  164,  122,  159,  140,  140,  123,   98,  124,  248,
      140,  124,  140,  165,  166,  174,  247,  167,  211,  211,
      246,  174,  143,  140,  140,  211,  211,  245,  174,  174,
      138,  140,  244,  141,  174,  174,  174,  243,  242,  241,
      240,  239,  174,  238,  237,  236,  235,  234,  233,  199,
       59,   59,   59,   59,   59,   59,   59,   67,   67,   67,
       67,   67,   67,   67,   70,   70,   70,   70,   70,   70,

       70,  120,  232,  120,  231,  120,  120,  120,  121,  230,
      121,  121,  121,  121,  121,  125,  125,  125,  127,  127,
      128,  229,  128,  128,  128,  128,  128,  130,  228,  227,
      130,  130,  130,  130,  137,  226,  137,  137,  137,  137,
      137,  225,  224,  223,  222,  221,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  198,  197,  196,  195,
      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      173,  172,  171,  170,  169,  168,  162,  126,  250,  161,

      160,  157,  156,  155,  154,  153,  152,  151,  150,  149,
      148,  147,  146,  145,  144,  142,  139,  136,  135,  134,
      133,  132,  131,  129,  126,  119,  114,  113,  108,  100,
       92,   84,   83,   75,  250,   11,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250

    } ;

static const flex_int16_t yy_chk[500] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    7,    8,   35,   35,   13,
        7,    8,   13,    3,    4,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    9,   10,
       18,   26,    9,   10,   37,   26,   27,   27,   45,   89,
       89,   45,   37,   37,   27,   27,   27,   27,   27,   27,
       28,   28,  262,   27,   36,   36,   39,   39,   28,   28,
       28,   28,   28,   28,   36,   50,   18,   28,   39,   39,
       18,   18,   18,   36,   50,   18,   44,   40,  254,   38,
       38,   47,   18,   47,   44,   49,   47,    9,   10,   38,

       40,   38,   38,   49,   54,   53,   54,   61,   38,   53,
       40,   61,   63,   74,   87,   63,   74,   90,   90,   93,
       93,   95,   96,   96,   98,  247,   87,   87,  115,   90,
       90,  132,  122,  115,   95,   95,  122,   98,  124,  245,
      140,  124,   95,  132,  132,  144,  244,  132,  190,  190,
      243,  174,   98,  140,  140,  211,  211,  242,  144,  144,
       93,  140,  241,   96,  174,  174,  144,  240,  238,  236,
      235,  234,  174,  233,  232,  231,  230,  229,  228,  174,
      251,  251,  251,  251,  251,  251,  251,  252,  252,  252,
      252,  252,  252,  252,  253,  253,  253,  253,  253,  253,

      253,  255,  225,  255,  224,  255,  255,  255,  256,  223,
      256,  256,  256,  256,  256,  257,  257,  257,  258,  258,
      259,  220,  259,  259,  259,  259,  259,  260,  219,  217,
      260,  260,  260,  260,  261,  216,  261,  261,  261,  261,
      261,  215,  212,  210,  207,  206,  205,  200,  198,  197,
      195,  194,  193,  192,  191,  189,  188,  186,  185,  184,
      182,  181,  180,  177,  176,  175,  171,  170,  169,  168,
      167,  166,  165,  164,  163,  161,  160,  159,  158,  157,
      156,  155,  153,  152,  151,  150,  149,  148,  147,  145,
      142,  139,  136,  135,  134,  133,  127,  125,  121,  118,

      116,  114,  113,  112,  111,  110,  107,  106,  105,  104,
      103,  102,  101,  100,   99,   97,   94,   81,   80,   79,
       78,   77,   72,   69,   65,   55,   52,   51,   48,   43,
       33,   25,   19,   16,   11,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int parser__flex_debug;
int parser__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *parser_text;
#line 1 "program_parser_v2020.flex"
#line 10 "program_parser_v2020.flex"
 #include <io.h>
 #define isatty _isatty
 #include "program.h"
 #include "program_parser_v2018.tab.hh"
 int program_lines=1;
 #define yylval program_lval
 #define MAX_INCLUDE_DEPTH 20
 YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
 int line_ptr_stack[MAX_INCLUDE_DEPTH];
 int include_stack_ptr=0;
 extern bool ParsingVHDL;
 extern bool DEMO_MODE;
/*
 #define yylex program_lex
 #define yyin program_in
 #define yyout program_out
 #define yy_init_buffer program_init_buffer
 #define yy_create_buffer program_create_buffer
 #define yy_load_buffer_state program_load_buffer_state
 #define yyrestart program_restart
 #define yy_switch_to_buffer program_switch_to_buffer
 #define yy_delete_buffer program_delete_buffer
*/




#line 755 "lex.parser_.c"

#define INITIAL 0
#define comment 1
#define include 2
#define target 3
#define vhdl 4

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int parser_lex_destroy ( void );

int parser_get_debug ( void );

void parser_set_debug ( int debug_flag  );

YY_EXTRA_TYPE parser_get_extra ( void );

void parser_set_extra ( YY_EXTRA_TYPE user_defined  );

FILE *parser_get_in ( void );

void parser_set_in  ( FILE * _in_str  );

FILE *parser_get_out ( void );

void parser_set_out  ( FILE * _out_str  );

			int parser_get_leng ( void );

char *parser_get_text ( void );

int parser_get_lineno ( void );

void parser_set_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int parser_wrap ( void );
#else
extern int parser_wrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( parser_text, (size_t) parser_leng, 1, parser_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( parser_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( parser_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, parser_in)) == 0 && ferror(parser_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(parser_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int parser_lex (void);

#define YY_DECL int parser_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after parser_text and parser_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! parser_in )
			parser_in = stdin;

		if ( ! parser_out )
			parser_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			parser_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				parser__create_buffer(parser_in,YY_BUF_SIZE );
		}

		parser__load_buffer_state( );
		}

	{
#line 42 "program_parser_v2020.flex"


		if (ParsingVHDL) BEGIN(vhdl);
#line 972 "lex.parser_.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of parser_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 251 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 436 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 45 "program_parser_v2020.flex"
{ BEGIN(INITIAL); return RIGHT_CURLY_BRACKET; };
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 46 "program_parser_v2020.flex"
{
			   int where=find(yytext,'>',0);
			   yylval.Variable=new action_variable(
						midstr(yytext,2,where-2),
						atoi(midstr(yytext,where+1,strlen(yytext)-where)));
			   return VARIABLE;
			};
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "program_parser_v2020.flex"
{ yylval.string=cpystr(yytext); return STRING; };
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 54 "program_parser_v2020.flex"
{ program_lines++; return NEWLINE; };
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 56 "program_parser_v2020.flex"
BEGIN(comment);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 57 "program_parser_v2020.flex"
/* eat up anything that is not a * or a newline */
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 58 "program_parser_v2020.flex"
/* eat up '*'s not followed by '/'s */
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 59 "program_parser_v2020.flex"
program_lines++;
	YY_BREAK
case YY_STATE_EOF(comment):
#line 60 "program_parser_v2020.flex"
{ fprintf(error_log,"Unexpected end of file inside comment\n"); exit(1); };
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 61 "program_parser_v2020.flex"
BEGIN(INITIAL);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 63 "program_parser_v2020.flex"
{ BEGIN(include); return INCLUDE; };
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 64 "program_parser_v2020.flex"
{ BEGIN(include); return INCLUDE_TEXT; };
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 65 "program_parser_v2020.flex"
/* eat up whitespace */
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 66 "program_parser_v2020.flex"
{ /* Catch the file name */
		    if (include_stack_ptr>=MAX_INCLUDE_DEPTH)
		    {
		       fprintf(error_log,"Includes nested too deeply\n");
		       exit(1);
		    };
		    include_stack[include_stack_ptr]=YY_CURRENT_BUFFER;
		    line_ptr_stack[include_stack_ptr++]=program_lines;
		    char *file_name=midstr(yytext,1,strlen(yytext)-2);
		    yyin=fopen(file_name,"r");
		    if (!yyin)
		    {
		       fprintf(error_log,"Cannot find include file %s\n",file_name);
		       exit(1);
		    }
		    yylval.string=file_name;
		    program_lines=1;
		    yy_switch_to_buffer(yy_create_buffer(yyin,YY_BUF_SIZE));
		    BEGIN(INITIAL); 
		    return FILE_NAME;
		};
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 87 "program_parser_v2020.flex"
{ yylval.string=cpystr(yytext); return ERROR; };
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 88 "program_parser_v2020.flex"
{ yylval.string=cpystr(yytext); return ERROR; };
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 89 "program_parser_v2020.flex"
yylval.string=cpystr(yytext); return ERROR; // Anything else
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 91 "program_parser_v2020.flex"
BEGIN(target); return TARGET_CODE_START;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 92 "program_parser_v2020.flex"
BEGIN(INITIAL); return TARGET_CODE_END;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 93 "program_parser_v2020.flex"
yylval.string=cpystr(yytext); return STRING;
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 94 "program_parser_v2020.flex"
program_lines++;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 96 "program_parser_v2020.flex"
return INPUT;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 97 "program_parser_v2020.flex"
return INOUT;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 98 "program_parser_v2020.flex"
return INTERNAL;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 99 "program_parser_v2020.flex"
return OUTPUT;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 100 "program_parser_v2020.flex"
return NAME;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 101 "program_parser_v2020.flex"
return MEMORY;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 102 "program_parser_v2020.flex"
return START;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 104 "program_parser_v2020.flex"
return HW;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 105 "program_parser_v2020.flex"
return SW;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 106 "program_parser_v2020.flex"
return DRIVER_MEMORY;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 107 "program_parser_v2020.flex"
return RATE;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 108 "program_parser_v2020.flex"
return KBPS;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 109 "program_parser_v2020.flex"
return MBPS;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 110 "program_parser_v2020.flex"
return GBPS;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 111 "program_parser_v2020.flex"
return KHZ;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 112 "program_parser_v2020.flex"
return MHZ;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 113 "program_parser_v2020.flex"
return GHZ;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 114 "program_parser_v2020.flex"
return RANGE;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 115 "program_parser_v2020.flex"
return TO;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 116 "program_parser_v2020.flex"
return CLOCK;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 117 "program_parser_v2020.flex"
return ASYNCH_RESET;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 118 "program_parser_v2020.flex"
return SYNCH_RESET;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 119 "program_parser_v2020.flex"
return AT;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 121 "program_parser_v2020.flex"
return BIT;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 122 "program_parser_v2020.flex"
return OTHERS;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 123 "program_parser_v2020.flex"
return ERROR;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 124 "program_parser_v2020.flex"
return BREAK;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 125 "program_parser_v2020.flex"
return INTERRUPT;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 126 "program_parser_v2020.flex"
return RESET;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 127 "program_parser_v2020.flex"
return SYNC;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 128 "program_parser_v2020.flex"
return COND;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 129 "program_parser_v2020.flex"
return IF;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 130 "program_parser_v2020.flex"
return ELSE;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 131 "program_parser_v2020.flex"
return ENDIF;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 133 "program_parser_v2020.flex"
yylval.string = yytext; return BIT_STRING;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 134 "program_parser_v2020.flex"
yylval.string = midstr(yytext,1,strlen(yytext)-2); return LONG_BIT_STRING;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 135 "program_parser_v2020.flex"
yylval.string = yytext; return HEX_NUMBER;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 136 "program_parser_v2020.flex"
yylval.string = midstr(yytext,1,strlen(yytext)-2); return LONG_HEX_NUMBER;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 137 "program_parser_v2020.flex"
yylval.string = yytext; return NUMBER;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 138 "program_parser_v2020.flex"
yylval.string = yytext; return CONSTANT;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 139 "program_parser_v2020.flex"
yylval.string = yytext; return LEXEM;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 140 "program_parser_v2020.flex"
return LEFT_BRACKET;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 141 "program_parser_v2020.flex"
return RIGHT_BRACKET;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 142 "program_parser_v2020.flex"
return LEFT_PARENTHESIS;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 143 "program_parser_v2020.flex"
return RIGHT_PARENTHESIS;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 144 "program_parser_v2020.flex"
return LEFT_CURLY_BRACKET;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 145 "program_parser_v2020.flex"
return RIGHT_CURLY_BRACKET;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 147 "program_parser_v2020.flex"
return CODE_START;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 148 "program_parser_v2020.flex"
return SEMICOLON;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 149 "program_parser_v2020.flex"
return COLON;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 150 "program_parser_v2020.flex"
return OR;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 151 "program_parser_v2020.flex"
return AND;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 152 "program_parser_v2020.flex"
return COND_AND;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 153 "program_parser_v2020.flex"
return EQUAL;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 154 "program_parser_v2020.flex"
return NOT_EQUAL;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 155 "program_parser_v2020.flex"
return DOUBLE_PERIOD;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 156 "program_parser_v2020.flex"
return PERIOD;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 157 "program_parser_v2020.flex"
return LESS_THAN;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 158 "program_parser_v2020.flex"
return GREATER_THAN;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 160 "program_parser_v2020.flex"
return ACTION;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 162 "program_parser_v2020.flex"
return ADD;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 163 "program_parser_v2020.flex"
return SUB;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 164 "program_parser_v2020.flex"
return MUL;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 165 "program_parser_v2020.flex"
return DIV;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 166 "program_parser_v2020.flex"
return SHR;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 168 "program_parser_v2020.flex"
return NOT;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 170 "program_parser_v2020.flex"
/* eat up comments */
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 171 "program_parser_v2020.flex"
/* eat up whitespace */
	YY_BREAK
case 89:
/* rule 89 can match eol */
YY_RULE_SETUP
#line 172 "program_parser_v2020.flex"
{ ++program_lines; /* eat up newlines */
		  if (DEMO_MODE)
		  {
			if (program_lines>100)
			{
				printf("Number of lines in Demo mode (100) exceeded\n");
				exit(1);
			}
		  }
		  if (ParsingVHDL) return NEWLINE;
		};
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 183 "program_parser_v2020.flex"
/* eat up carridge returns (ASCII 0d) in DOS-files */
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 184 "program_parser_v2020.flex"
{ printf("\n Unknown Keyword %s",yylval.string = yytext);
		  return ERROR; };
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(include):
case YY_STATE_EOF(target):
case YY_STATE_EOF(vhdl):
#line 187 "program_parser_v2020.flex"
{ /* Found an end of file */
		  if (--include_stack_ptr<0)
		  {
		     yyterminate();
		  }
		  else
		  {
		     FILE *tmp;
		     tmp=yyin;
		     yy_switch_to_buffer(include_stack[include_stack_ptr]);
		     program_lines=line_ptr_stack[include_stack_ptr];
		     fclose(tmp);
		  };
		  return END_OF_FILE;
		};
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 202 "program_parser_v2020.flex"
ECHO;
	YY_BREAK
#line 1555 "lex.parser_.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed parser_in at a new source and called
			 * parser_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = parser_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( parser_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * parser_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of parser_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					parser_realloc((void *) b->yy_ch_buf,(yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			parser_restart(parser_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) parser_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,(yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 251 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 251 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 250);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up parser_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					parser_restart(parser_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( parser_wrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve parser_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void parser_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        parser_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            parser__create_buffer(parser_in,YY_BUF_SIZE );
	}

	parser__init_buffer(YY_CURRENT_BUFFER,input_file );
	parser__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void parser__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		parser_pop_buffer_state();
	 *		parser_push_buffer_state(new_buffer);
     */
	parser_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	parser__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (parser_wrap()) processing, but the only time this flag
	 * is looked at is after parser_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void parser__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	parser_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE parser__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) parser_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in parser__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) parser_alloc((yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in parser__create_buffer()" );

	b->yy_is_our_buffer = 1;

	parser__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with parser__create_buffer()
 * 
 */
    void parser__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		parser_free((void *) b->yy_ch_buf  );

	parser_free((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a parser_restart() or at EOF.
 */
    static void parser__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	parser__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then parser__init_buffer was _probably_
     * called from parser_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void parser__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		parser__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void parser_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	parser_ensure_buffer_stack();

	/* This block is copied from parser__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from parser__switch_to_buffer. */
	parser__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void parser_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	parser__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		parser__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void parser_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)parser_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in parser_ensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)parser_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in parser_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE parser__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) parser_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in parser__scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	parser__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to parser_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       parser__scan_bytes() instead.
 */
YY_BUFFER_STATE parser__scan_string (const char * yystr )
{
    
	return parser__scan_bytes(yystr,(int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to parser_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE parser__scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) parser_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in parser__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = parser__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in parser__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up parser_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		parser_text[parser_leng] = (yy_hold_char); \
		(yy_c_buf_p) = parser_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		parser_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int parser_get_lineno  (void)
{
    
    return parser_lineno;
}

/** Get the input stream.
 * 
 */
FILE *parser_get_in  (void)
{
        return parser_in;
}

/** Get the output stream.
 * 
 */
FILE *parser_get_out  (void)
{
        return parser_out;
}

/** Get the length of the current token.
 * 
 */
int parser_get_leng  (void)
{
        return parser_leng;
}

/** Get the current token.
 * 
 */

char *parser_get_text  (void)
{
        return parser_text;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void parser_set_lineno (int  _line_number )
{
    
    parser_lineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see parser__switch_to_buffer
 */
void parser_set_in (FILE *  _in_str )
{
        parser_in = _in_str ;
}

void parser_set_out (FILE *  _out_str )
{
        parser_out = _out_str ;
}

int parser_get_debug  (void)
{
        return parser__flex_debug;
}

void parser_set_debug (int  _bdebug )
{
        parser__flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from parser_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    parser_in = stdin;
    parser_out = stdout;
#else
    parser_in = NULL;
    parser_out = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * parser_lex_init()
     */
    return 0;
}

/* parser_lex_destroy is for both reentrant and non-reentrant scanners. */
int parser_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		parser__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		parser_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	parser_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * parser_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *parser_alloc (yy_size_t  size )
{
			return malloc(size);
}

void *parser_realloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void parser_free (void * ptr )
{
			free( (char *) ptr );	/* see parser_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 202 "program_parser_v2020.flex"


int yywrap(void)
{
   return 1;
};

