`timescale 1ns/1ps

module dtekv_tb (
    input  logic        clk,
    input  logic        reset_n,  // active-low reset

    // ===== Instruction port to CPU =====
    input  logic [31:0] avm_instr_read_adr, 
    input  logic        avm_instr_read,
    output logic [31:0] avm_instr_read_data, 
    output logic        avm_instr_read_waitreq,

    // ===== Control slave (start CPU) =====
    output logic [7:0]  avm_ctrl_slave_data,
    output logic        avm_ctrl_slave_write,
    input  logic        avm_ctrl_slave_waitreq,

    // ===== Data port to CPU =====
    input  logic [31:0] avm_data_adr,
    input  logic        avm_data_read,
    input  logic        avm_data_write,
    input  logic [31:0] avm_data_write_data,
    input  logic [3:0]  avm_data_write_byten,
    output logic [31:0] avm_data_read_data,
    output logic        avm_data_waitreq
);

    //  Instruction memory (IMEM)

    // Address mapping:
    //   - CPU uses byte address in avm_instr_read_adr
    //   - IMEM is word-addressed (32-bit words)
    //   - Drop the lowest two bits for word index
    //   - Truncate to 14 bits as required by IMEM IP
    logic [15:0] imem_addr;
    logic [31:0] imem_q;

    assign imem_addr = avm_instr_read_adr[15:2];  // adjust if your mapping differs

    // IMEM IP instance (generated by Quartus)
    IMEM u_imem (
        .address (imem_addr),
        .clock   (clk),
        .q       (imem_q)
    );

    // Always-ready instruction memory (0 wait states).
    // Assumes IMEM is configured for asynchronous/combinational read
    // (q reflects current address without extra cycle of latency).
    always_comb begin
        avm_instr_read_data    = imem_q;
        avm_instr_read_waitreq = 1'b0;
    end

    //  Data memory (DMEM)
    logic [15:0] dmem_addr;
    logic [31:0] dmem_wdata;
    logic        dmem_wren;
    logic [31:0] dmem_q;

    // Address mapping:
    //   - CPU uses byte address in avm_data_adr
    //   - DMEM is word-addressed (32-bit words)
    //   - Drop the lowest two bits for word index
    //   - Truncate to 16 bits as required by DMEM IP
    assign dmem_addr = avm_data_adr[17:2];  // adjust if your mapping differs

    // DMEM IP instance (generated by Quartus)
    DMEM u_dmem (
        .address (dmem_addr),
        .clock   (clk),
        .data    (dmem_wdata),
        .wren    (dmem_wren),
        .q       (dmem_q)
    );

    // Data-path adaptation:
    // - Reads are always 0-wait-state (combinational read assumed).
    // - Writes support byte enables via read-modify-write:
    //   * read old word from dmem_q
    //   * merge selected bytes from avm_data_write_data
    //   * write back full 32-bit word to DMEM
    always_comb begin
        // Default: no write, pass-through read, no back-pressure.
        dmem_wren          = 1'b0;
        dmem_wdata         = 32'h0000_0000;
        avm_data_read_data = dmem_q;
        avm_data_waitreq   = 1'b0;

        // Handle write transactions
        if (avm_data_write) begin
            // Start from the current word at this address
            logic [31:0] merged;
            merged = dmem_q;

            // Apply byte enables (little-endian: byte 0 is bits [7:0])
            if (avm_data_write_byten[0]) begin
                merged[7:0] = avm_data_write_data[7:0];
            end
            if (avm_data_write_byten[1]) begin
                merged[15:8] = avm_data_write_data[15:8];
            end
            if (avm_data_write_byten[2]) begin
                merged[23:16] = avm_data_write_data[23:16];
            end
            if (avm_data_write_byten[3]) begin
                merged[31:24] = avm_data_write_data[31:24];
            end

            dmem_wren  = 1'b1;
            dmem_wdata = merged;
        end
    end

    //  Control slave: send a single "start" command (0xF0)
    typedef enum logic [1:0] {
        CTRL_IDLE     = 2'b00,
        CTRL_SEND     = 2'b01,
        CTRL_DONE     = 2'b10
    } ctrl_state_t;

    ctrl_state_t ctrl_state;

    // Generate one 0xF0 write after reset is released and waitreq=0.
    always_ff @(posedge clk or negedge reset_n) begin
        if (!reset_n) begin
            ctrl_state          <= CTRL_IDLE;
            avm_ctrl_slave_data <= 8'h00;
            avm_ctrl_slave_write<= 1'b0;
        end else begin
            case (ctrl_state)
                CTRL_IDLE: begin
                    // Wait until the control slave is ready
                    if (!avm_ctrl_slave_waitreq) begin
                        avm_ctrl_slave_data  <= 8'hF0;  // start command
                        avm_ctrl_slave_write <= 1'b1;   // assert write for one cycle
                        ctrl_state           <= CTRL_SEND;
                    end else begin
                        avm_ctrl_slave_write <= 1'b0;
                    end
                end

                CTRL_SEND: begin
                    // Deassert write after one clock
                    avm_ctrl_slave_write <= 1'b0;
                    ctrl_state           <= CTRL_DONE;
                end

                CTRL_DONE: begin
                    // Nothing more to do; keep outputs stable
                    avm_ctrl_slave_write <= 1'b0;
                end

                default: begin
                    ctrl_state           <= CTRL_IDLE;
                    avm_ctrl_slave_write <= 1'b0;
                end
            endcase
        end
    end

endmodule

